<?php

namespace Database\Seeders;

use App\Models\Category;
use Illuminate\Database\Seeder;

class CategorySeeder extends Seeder
{
    public function run(): void
    {
        // Définir manuellement les catégories spécifiques
        $categories = collect([
            'Direction Générale',
            'Ressources Humaines',
            'Secrétariat / Assistance Administrative',
            'Gestion de Projet',
            'Comptabilité / Finance',
            'Audit et Contrôle de Gestion',
            'Développement Web et Mobile',
            'Administration Systèmes et Réseaux',
            'Support Technique et Helpdesk',
            'Cybersécurité',
            'Data Science et Big Data',
            'Intelligence Artificielle et Machine Learning',
            'Marketing Digital',
            'Relations Publiques',
            'Publicité et Création',
            'Gestion des Médias Sociaux',
            'Études de Marché',
            'Communication d\'Entreprise',
            'Représentation Commerciale',
            'Gestion de Compte / Account Management',
            'Business Development',
            'Vente en Détail',
            'Vente en Ligne / E-commerce',
            'Gestion de Magasin',
            'Analyse Financière',
            'Comptabilité Générale',
            'Trésorerie',
            'Contrôle de Gestion',
            'Conseil en Investissement',
            'Audit Comptable et Financier',
            'Génie Civil',
            'Génie Électrique',
            'Génie Mécanique',
            'Automatisme et Robotique',
            'Gestion de Production',
            'Maintenance Industrielle',
            'Gestion des Approvisionnements',
            'Transport de Marchandises',
            'Logistique et Chaîne d\'Approvisionnement',
            'Gestion des Stocks',
            'Conducteurs et Chauffeurs',
            'Distribution',
            'Médecine Générale',
            'Soins Infirmiers',
            'Pharmacie',
            'Travail Social',
            'Nutrition et Diététique',
            'Psychologie',
            'Enseignement Primaire et Secondaire',
            'Enseignement Supérieur',
            'Formation Professionnelle',
            'E-learning',
            'Recherche Scientifique',
            'Administration Scolaire',
            'Gestion Hôtelière',
            'Tourisme et Loisirs',
            'Restauration',
            'Réception et Service Client',
            'Animation Touristique',
            'Gestion d\'Événements',
            'Art et Design',
            'Mode et Textile',
            'Artisanat Traditionnel',
            'Photographie',
            'Production Audiovisuelle',
            'Musique et Spectacle',
            'Construction',
            'Architecture',
            'Travaux Publics',
            'Génie Civil',
            'Électricité Bâtiment',
            'Plomberie et Sanitaires',
            'Agriculture',
            'Élevage',
            'Pêche',
            'Gestion de l\'Environnement',
            'Agroalimentaire',
            'Foresterie',
            'Nettoyage et Entretien',
            'Garde d\'Enfants',
            'Aide à Domicile',
            'Soutien Scolaire',
            'Coiffure et Esthétique',
            'Sécurité',
        ]);

        $categories->each(fn($category) => Category::firstOrCreate(['name' => $category]));
    }
}
